# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  ulimits:
    nofile:
      soft: 65536
      hard: 65536
  environment:
      - ES_HEAP_SIZE=1g # set to 50% of mem_limit, but no more than 31g

#  volumes:
#    - ./elk:/elk
