# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up
version: '2'
services:
  elk:
    build: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
    ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
    mem_limit: 1000000000
  

#  volumes:
#    - ./elk:/elk
